# Generated by Django 4.2 on 2024-01-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercustom",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
