# Generated by Django 4.2 on 2024-01-05 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_loginfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginfo",
            name="isadmin",
            field=models.BooleanField(default=False),
        ),
    ]
