# Generated by Django 4.2 on 2024-01-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                ("admin_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=75, unique=True)),
                ("password", models.CharField(max_length=75)),
            ],
            options={
                "db_table": "admin",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Announcements",
            fields=[
                (
                    "announcement_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "creationdate",
                    models.DateTimeField(auto_now_add=True, db_column="creationDate"),
                ),
                ("title", models.CharField(max_length=50)),
                ("contents", models.CharField(max_length=45)),
            ],
            options={
                "db_table": "announcements",
                "managed": False,
            },
        ),
    ]
