# Generated by Django 4.2 on 2024-01-05 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("announcement", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Admin",
        ),
    ]
