# Generated by Django 4.2 on 2024-01-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                ("board_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=75)),
                ("contents", models.TextField()),
                ("creationdate", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "board",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                ("comment_id", models.AutoField(primary_key=True, serialize=False)),
                ("contents", models.TextField()),
                ("creationdate", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "comments",
                "managed": False,
            },
        ),
    ]
